services:
  client:
    build:
      context: ./client
    container_name: yolo-client
    ports:
      - "3000:80"
    networks:
      - appnet
    depends_on:
      server:
        condition: service_started
    environment:
      - REACT_APP_BACKEND_URL=http://server:5002

  server:
    build:
      context: ./backend  
    container_name: yolo-server
    ports:
      - "5002:5002"
    networks:
      - appnet
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI}
      - PORT=5002
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: yolo-redis
    networks:
      - appnet

networks:
  appnet:
    driver: bridge