version: '3.8'

services:
  client:
    build:
      context: ./client
    container_name: client
    ports:
      - "3000:80"
    networks:
      - appnet
    depends_on:
      server:
        condition: service_started
    environment:
      - BACKEND_URL=http://host.docker.internal:5002

  server:
    build:
      context: ./backend
    container_name: server
    network_mode: "host"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI}
      - PORT=5002
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - appnet

networks:
  appnet:
    driver: bridge