version: '3.8'

services:
  client:
    build:
      context: ./client
    container_name: client
    ports:
      - "3000:80"
    networks:
      - appnet
    depends_on:
      server:
        condition: service_started
    environment:
      - BACKEND_URL=http://host.docker.internal:5002

  server:
    build:
      context: ./backend
    container_name: server
    network_mode: "host"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI}
      - PORT=5002
    depends_on:
      - redis
      - mongodb

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - appnet

  mongodb:
    image: mongo:7.0-jammy
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    networks:
      - appnet
    environment:
      - MONGO_INITDB_DATABASE=yolo
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:data/configdb
    command: mongod --logpath=/dev/null --quiet

networks:
  appnet:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local