---
- name: Debug app_dir variable
  debug:
    var: app_dir
  tags: [debug, full_deploy]

- name: Check if backend directory exists
  stat:
    path: "{{ app_dir }}/backend"
  register: backend_dir
  tags: [debug, full_deploy]

- name: Pull server image from DockerHub
  docker_image:
    name: "{{ server_image }}"
    source: pull
    state: present
    force_source: yes
  tags: [pull, full_deploy]

- name: Start server container
  docker_container:
    name: "{{ server_container_name }}"
    image: "{{ server_image }}"
    networks:
      - name: "{{ network_name }}"
    ports:
      - "{{ server_port }}:5002"
    env:
      NODE_ENV: production
      MONGODB_URI: "{{ ansible_env.MONGODB_URI | default('mongodb://localhost:27017/yolo') }}"
      PORT: "{{ server_port | string }}"
    state: started
    restart_policy: always
  tags: [server, full_deploy]