apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: yolo
  labels:
    app: frontend
    component: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        component: ui
    spec:
      containers:
      - name: frontend
        image: doc0pz/yolo-client:v1.2.1
        ports:
        - containerPort: 80
          name: http-port
        env:
        - name: REACT_APP_BACKEND_URL
          value: "http://backend-service:5002"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10