apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: yolo
  labels:
    app: mongodb
spec:
  clusterIP: None
  ports:
  - port: 27017
    targetPort: 27017
    name: mongo-port
  selector:
    app: mongodb
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: yolo
  labels:
    app: redis
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
    name: redis-port
  selector:
    app: redis
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: yolo
  labels:
    app: backend
spec:
  type: ClusterIP
  ports:
  - port: 5002
    targetPort: 5002
    name: http-port
  selector:
    app: backend
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: yolo
  labels:
    app: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    name: http-port
  selector:
    app: frontend